import {
  Activity,
  BarChart3,
  Bell,
  Bike,
  BookOpen,
  Bookmark,
  Briefcase,
  Building,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  Check,
  Clock,
  Cloud,
  Code2,
  Coffee,
  CreditCard,
  Database,
  Download,
  Dumbbell,
  FileText,
  Folder,
  Gamepad2,
  Gift,
  Globe,
  Headphones,
  Heart,
  Home,
  Image,
  Key,
  Laptop,
  Lightbulb,
  Link,
  ListTodo,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageSquare,
  Mic,
  Monitor,
  Music,
  Package,
  Palette,
  Phone,
  PieChart,
  Plane,
  Play,
  Presentation,
  Radio,
  Rss,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Table2,
  Terminal,
  TrendingUp,
  Trophy,
  Upload,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { ShortcutIcon } from './types';

export interface ShortcutIconOption {
  id: ShortcutIcon;
  label: string;
  Icon: LucideIcon;
}

export const shortcutIconOptions: ShortcutIconOption[] = [
  { id: 'link', label: '链接', Icon: Link },
  { id: 'globe', label: '网站', Icon: Globe },
  { id: 'mail', label: '邮箱', Icon: Mail },
  { id: 'calendar', label: '日历', Icon: CalendarDays },
  { id: 'clock', label: '时间', Icon: Clock },
  { id: 'file', label: '文档', Icon: FileText },
  { id: 'folder', label: '文件夹', Icon: Folder },
  { id: 'table', label: '表格', Icon: Table2 },
  { id: 'presentation', label: '演示', Icon: Presentation },
  { id: 'cloud', label: '云端', Icon: Cloud },
  { id: 'download', label: '下载', Icon: Download },
  { id: 'upload', label: '上传', Icon: Upload },
  { id: 'check', label: '任务', Icon: Check },
  { id: 'list', label: '列表', Icon: ListTodo },
  { id: 'bookmark', label: '书签', Icon: Bookmark },
  { id: 'star', label: '星标', Icon: Star },
  { id: 'heart', label: '收藏', Icon: Heart },
  { id: 'lightbulb', label: '灵感', Icon: Lightbulb },
  { id: 'code', label: '代码', Icon: Code2 },
  { id: 'terminal', label: '终端', Icon: Terminal },
  { id: 'database', label: '数据库', Icon: Database },
  { id: 'laptop', label: '笔记本电脑', Icon: Laptop },
  { id: 'monitor', label: '显示器', Icon: Monitor },
  { id: 'smartphone', label: '手机', Icon: Smartphone },
  { id: 'wifi', label: '网络', Icon: Wifi },
  { id: 'shield', label: '安全', Icon: Shield },
  { id: 'lock', label: '锁定', Icon: Lock },
  { id: 'key', label: '密钥', Icon: Key },
  { id: 'chart', label: '柱状图', Icon: BarChart3 },
  { id: 'pie', label: '饼图', Icon: PieChart },
  { id: 'trend', label: '趋势', Icon: TrendingUp },
  { id: 'calculator', label: '计算器', Icon: Calculator },
  { id: 'briefcase', label: '工作', Icon: Briefcase },
  { id: 'building', label: '公司', Icon: Building },
  { id: 'user', label: '用户', Icon: User },
  { id: 'users', label: '团队', Icon: Users },
  { id: 'message', label: '消息', Icon: MessageSquare },
  { id: 'phone', label: '电话', Icon: Phone },
  { id: 'image', label: '图片', Icon: Image },
  { id: 'camera', label: '相机', Icon: Camera },
  { id: 'palette', label: '设计', Icon: Palette },
  { id: 'book', label: '阅读', Icon: BookOpen },
  { id: 'play', label: '播放', Icon: Play },
  { id: 'video', label: '视频', Icon: Video },
  { id: 'music', label: '音乐', Icon: Music },
  { id: 'headphones', label: '耳机', Icon: Headphones },
  { id: 'mic', label: '麦克风', Icon: Mic },
  { id: 'radio', label: '广播', Icon: Radio },
  { id: 'rss', label: '订阅', Icon: Rss },
  { id: 'shopping', label: '购物袋', Icon: ShoppingBag },
  { id: 'shopping-cart', label: '购物车', Icon: ShoppingCart },
  { id: 'credit-card', label: '银行卡', Icon: CreditCard },
  { id: 'wallet', label: '钱包', Icon: Wallet },
  { id: 'package', label: '包裹', Icon: Package },
  { id: 'gift', label: '礼物', Icon: Gift },
  { id: 'home', label: '家庭', Icon: Home },
  { id: 'coffee', label: '咖啡', Icon: Coffee },
  { id: 'utensils', label: '餐饮', Icon: Utensils },
  { id: 'plane', label: '飞机', Icon: Plane },
  { id: 'car', label: '汽车', Icon: Car },
  { id: 'bike', label: '骑行', Icon: Bike },
  { id: 'map', label: '地图', Icon: Map },
  { id: 'map-pin', label: '地点', Icon: MapPin },
  { id: 'activity', label: '活动', Icon: Activity },
  { id: 'dumbbell', label: '健身', Icon: Dumbbell },
  { id: 'game', label: '游戏', Icon: Gamepad2 },
  { id: 'trophy', label: '奖杯', Icon: Trophy },
  { id: 'bell', label: '提醒', Icon: Bell },
  { id: 'zap', label: '效率', Icon: Zap },
];

export const shortcutIconMap = Object.fromEntries(
  shortcutIconOptions.map(({ id, Icon }) => [id, Icon]),
) as Record<ShortcutIcon, LucideIcon>;
